In [2]:
import itertools as it
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import functools
import math
import fractions


from numpy import linalg as LA
#МПИ
def SimpleIteration(R, x, F):#R - матрица, x - столбец, F - правая часть (столбец)
    T = R@x + F
    return (T)
#МПИ k раз
def SimpleIterations(R,x,F,k):#R - матрица, x - столбец с которого итерируемся, F - правая часть(столбец), k- число итераций
    for i in range(k):
        x = SimpleIteration(R, x, F)
    return x
#k итераций методом Гаусса - Якоби 
def GaussJacobyIterations(A, x, F, k):#A - матрица, x - столбец с которого итерируемся, F - правая часть, k- число итераций
            D = np.diag(np.diag(A))
            Q = np.identity(len(A))
            G = np.identity(len(A))
            for i in range(len(A)):
                Q[i][i] = 1/D[i][i]
            R = -Q@(A - D)
            f = Q@F
            return SimpleIterations(R, x, f, k)
#Скалярное произведение
def scal(u, v):#u, v - сомножители (столбцы)
    return u@np.transpose(v)
#Итерационный метод вычисления максимального собственного вектора
def MaxEigenIterations(A, x, k):#A - матрица, x - вектор с которого итерируемся, k -число итераций
    u = SimpleIterations(A, x, 0, k-1)
    return scal(SimpleIteration(A,u,0), u)/scal(u, u)

In [25]:
A = np.array([[20, -1, 2, -3], [2, 20, -3, 4], [-3, 2, 20, -1],[-3,2,-1,20]], float)
D = np.diag(np.diag(A))
E = np.identity(4)
R = LA.inv(D)@A - E
print(R)
LA.norm(R, np.inf)
LA.norm(LA.inv((np.tril(A)@np.triu(A))))

[[ 0.   -0.05  0.1  -0.15]
 [ 0.1   0.   -0.15  0.2 ]
 [-0.15  0.1   0.   -0.05]
 [-0.15  0.1  -0.05  0.  ]]


0.0051242326227329835

In [16]:
def AbsMax(A):
    return np.max(np.array([np.max(A), -np.min(A)]))

In [35]:
A = np.array([[3, 1], [1, 2]])
x = np.array([0, 0])
F = np.array([1, -1])
np.linalg.solve(A, F)

array([ 0.6, -0.8])

In [74]:
r = np.array([[0.1, 0.20, 0.0], [0.20, -0.10, 0.10], [-0.30, 0.0, 0.20]])
f = np.array([-3.0, 2.0, -1.0])
R = np.array([[0,2/9,0], [2/11, 0, 1/11], [-3/8, 0, 0]])
F = np.array([-30/9, 20/11, -10/8])
x = np.array([0, 0, 0])
print(r)
for i in range(100):
    x = r@x + f
print("1:", x)
for i in range(100):
    x = R@x + F
print("2:",x)


[[ 0.1  0.2  0. ]
 [ 0.2 -0.1  0.1]
 [-0.3  0.   0.2]]
1: [-3.05483029  1.25326371 -0.10443864]
2: [-3.05483029  1.25326371 -0.10443864]


In [40]:
def IntVect(v, maxnum):
    answ = 0
    norm = np.linalg.norm(v)
    for k in range(1, maxnum):
        q = k*v
        approx = np.array([0 for i in range(len(v))])
        for i in range(len(v)):
            if (q[i] - int(q[i])) < (int(q[i]) + 1 - q[i]):
                approx[i] = int(q[i])
            else:
                approx[i] = int(q[i]) + 1
        if k == 1:
            norm = np.linalg.norm(q - approx, 2)
        else:
            if np.linalg.norm(q - approx) < norm:
                answ = approx
                norm = np.linalg.norm(q -approx)
    return (answ, q)


In [120]:
def SpecRad (A):
        return AbsMax(np.linalg.eig(A)[0])

In [145]:
A = np.array([[2, 1],[1, 2]])
OptRel(A)

[[ 0.  -0.5]
 [-0.5  0. ]]
0.5000000000000001
1.0717967697244908


0

In [144]:
def OptRel(A):
    D = np.diag(A)
    Q = np.identity(len(A))
    G = np.identity(len(A))
    for i in range(len(A)):
        Q[i][i] = 1/D[i]
        G[i][i] = D[i]
    R = -Q@(A - G)
    return (2/(1 + (1 - (SpecRad(R))**2)**0.5)
    


3

In [14]:
A = np.array([[2, 1], [1, 2]], float)
f = np.array([1, 0], float)
x = np.array([0, 0], float)
GaussJacobyIterations(A, x, f, 100)

[[ 0.  -0.5]
 [-0.5  0. ]] [0.5 0. ] [0. 0.]


array([ 0.66666667, -0.33333333])

$u^{(s+1)} = u^{(s)} + \tau (f - Au^{(s)})$

Метод вращений.

$T^TAT = \Lambda$

$\tan (2\alpha) = \frac{2a_{ij}}{a_{ii} - a_{jj}}$

МНК:

$\Phi(\vec{u}) = \Sigma_i (\Sigma_j a_{ij}u_j - f_i)^2 \rightarrow min$

$A_{nxm}\vec{u}_n = \vec{f}_m$

$(A*A)_{nxn}\vec{u} = (A*f)_n$

Полиномы Чебышева $T_j(x)$
<br>
Их линейная комбинация:
<br>
$P_k(x) = \sum_{j = 0}^{k} c_jT_j(x)$

In [5]:
import numpy as np
from numpy import polynomial as POL

In [8]:
#x - вектор точек в которых необходимо узнать значения линейной комбинации многочленов Чебышева
#c - вектор коэффициентов перед многочленами Чебышева (см.выше)
x = np.array([3])
c = np.array([2])
POL.chebyshev.chebval(x,c)

array([2.])

$\textbf{Метод наискорейшего спуска}$

In [19]:
#A - матрица, u - начальный ветор, f - правая часть, k - число итераций
def desc (A, u, f ,k):
    for i in range(k):
        r = A@u - f
        if(scal(r,r) == 0):
            return u
        t = scal(r, r)/scal(A@r, r)
        u = u - t*r
    return u


In [23]:
#A - матрица, u - начальный ветор, f - правая часть, k - число итераций
def minnev (A, u, f ,k):
    for i in range(k):
        r = A@u - f
        if(scal(r,r) == 0):
            return u
        t = scal(A@r, r)/scal(A@r, A@r)
        u = u - t*r
    return u


In [39]:
A = np.array([[10*j + i for i in range(10)] for j in range(10)])
print(A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [42]:
#Интерполяция многочленом проходящим через заданную сетку
def SimplePolynomialInterpolation(x, y):
    A = np.array([[x[j]**i for i in range(len(y))] for j in range(len(x))])
    return np.linalg.solve(A, y)

In [47]:
x = np.array([0, 1])
y = np.array([1, 0])
SimplePolynomialInterpolation(x, y)

array([ 1., -1.])

In [57]:
def integer_collinear_vector(numbers, max_denominator=1000000):
    t = np.array([])
    for i in range(len(numbers)):
        if numbers[i] != 0:
            a = np.array([numbers[i]])
            t = np.concatenate((t, a))
    norma = np.min(t)
    numbers = [num / norma for num in numbers]
    fracts = [fractions.Fraction(f).limit_denominator(max_denominator) for f in numbers]
    denoms = [f.denominator for f in fracts]
    denoms_gcd = functools.reduce(math.gcd, denoms)
    denoms_lcm = functools.reduce(lambda a, b: a*b, [d // denoms_gcd for d in denoms]) * denoms_gcd
    result_integers = [f.numerator * (denoms_lcm // f.denominator) for f in fracts]
    return result_integers

In [62]:
A = np.array([[18, 6, 0], [6, 6, -7], [0, -7, 18]])
B = np.linalg.inv(A)
D = np.di
E = np.identity(3)
np.linalg.eig(B)

(array([1.        , 0.05555556, 0.04347826]),
 array([[-3.10252614e-01,  7.59256602e-01, -5.72077554e-01],
        [ 8.79049073e-01, -9.23163656e-16, -4.76731295e-01],
        [ 3.61961383e-01,  6.50791373e-01,  6.67423812e-01]]))

In [49]:
33.7/3**0.5

19.456704071690393

In [1]:
def f1(a, b):
    return a + b
def b(f, x, y):
    return f(x, y)

In [4]:
b(f1, 1, 2)

3

In [7]:
for i in range(1):
    print(i)

0
