In [7]:
import itertools as it
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import functools
import math
import fractions
from scipy.interpolate import lagrange

from numpy import linalg as LA
#МПИ
def SimpleIteration(R, x, F):#R - матрица, x - столбец, F - правая часть (столбец)
    T = R@x + F
    return (T)
#МПИ k раз
def SimpleIterations(R,x,F,k):#R - матрица, x - столбец с которого итерируемся, F - правая часть(столбец), k- число итераций
    for i in range(k):
        x = SimpleIteration(R, x, F)
    return x
#k итераций методом Гаусса - Якоби 
def GaussJacobyIterations(A, x, F, k):#A - матрица, x - столбец с которого итерируемся, F - правая часть, k- число итераций
            D = np.diag(np.diag(A))
            Q = np.identity(len(A))
            G = np.identity(len(A))
            for i in range(len(A)):
                Q[i][i] = 1/D[i][i]
            R = -Q@(A - D)
            f = Q@F
            return SimpleIterations(R, x, f, k)
#Скалярное произведение
def scal(u, v):#u, v - сомножители (столбцы)
    return u@np.transpose(v)
#Итерационный метод вычисления максимального собственного вектора
def MaxEigenIterations(A, x, k):#A - матрица, x - вектор с которого итерируемся, k -число итераций
    u = SimpleIterations(A, x, 0, k-1)
    return scal(SimpleIteration(A,u,0), u)/scal(u, u)

In [2]:
A = np.array([[20, -1, 2, -3], [2, 20, -3, 4], [-3, 2, 20, -1],[-3,2,-1,20]], float)
D = np.diag(np.diag(A))
E = np.identity(4)
R = LA.inv(D)@A - E
print(R)
LA.norm(R, np.inf)
LA.norm(LA.inv((np.tril(A)@np.triu(A))))

[[ 0.   -0.05  0.1  -0.15]
 [ 0.1   0.   -0.15  0.2 ]
 [-0.15  0.1   0.   -0.05]
 [-0.15  0.1  -0.05  0.  ]]


0.0051242326227329835

In [3]:
def AbsMax(A):
    return np.max(np.array([np.max(A), -np.min(A)]))

In [4]:
A = np.array([[3, 1], [1, 2]])
x = np.array([0, 0])
F = np.array([1, -1])
np.linalg.solve(A, F)

array([ 0.6, -0.8])

In [5]:
r = np.array([[0.1, 0.20, 0.0], [0.20, -0.10, 0.10], [-0.30, 0.0, 0.20]])
f = np.array([-3.0, 2.0, -1.0])
R = np.array([[0,2/9,0], [2/11, 0, 1/11], [-3/8, 0, 0]])
F = np.array([-30/9, 20/11, -10/8])
x = np.array([0, 0, 0])
print(r)
for i in range(100):
    x = r@x + f
print("1:", x)
for i in range(100):
    x = R@x + F
print("2:",x)


[[ 0.1  0.2  0. ]
 [ 0.2 -0.1  0.1]
 [-0.3  0.   0.2]]
1: [-3.05483029  1.25326371 -0.10443864]
2: [-3.05483029  1.25326371 -0.10443864]


In [6]:
def IntVect(v, maxnum):
    answ = 0
    norm = np.linalg.norm(v)
    for k in range(1, maxnum):
        q = k*v
        approx = np.array([0 for i in range(len(v))])
        for i in range(len(v)):
            if (q[i] - int(q[i])) < (int(q[i]) + 1 - q[i]):
                approx[i] = int(q[i])
            else:
                approx[i] = int(q[i]) + 1
        if k == 1:
            norm = np.linalg.norm(q - approx, 2)
        else:
            if np.linalg.norm(q - approx) < norm:
                answ = approx
                norm = np.linalg.norm(q -approx)
    return (answ, q)


In [7]:
def SpecRad (A):
        return AbsMax(np.linalg.eig(A)[0])

In [8]:
A = np.array([[2, 1],[1, 2]])
OptRel(A)

NameError: name 'OptRel' is not defined

In [ ]:
def OptRel(A):
    D = np.diag(A)
    Q = np.identity(len(A))
    G = np.identity(len(A))
    for i in range(len(A)):
        Q[i][i] = 1/D[i]
        G[i][i] = D[i]
    R = -Q@(A - G)
    return (2/(1 + (1 - (SpecRad(R))**2)**0.5)
    


In [ ]:
A = np.array([[2, 1], [1, 2]], float)
f = np.array([1, 0], float)
x = np.array([0, 0], float)
GaussJacobyIterations(A, x, f, 100)

$u^{(s+1)} = u^{(s)} + \tau (f - Au^{(s)})$

Метод вращений.

$T^TAT = \Lambda$

$\tan (2\alpha) = \frac{2a_{ij}}{a_{ii} - a_{jj}}$

МНК:

$\Phi(\vec{u}) = \Sigma_i (\Sigma_j a_{ij}u_j - f_i)^2 \rightarrow min$

$A_{nxm}\vec{u}_n = \vec{f}_m$

$(A*A)_{nxn}\vec{u} = (A*f)_n$

Полиномы Чебышева $T_j(x)$
<br>
Их линейная комбинация:
<br>
$P_k(x) = \sum_{j = 0}^{k} c_jT_j(x)$

In [ ]:
import numpy as np
from numpy import polynomial as POL

In [2]:
#x - вектор точек в которых необходимо узнать значения линейной комбинации многочленов Чебышева
#c - вектор коэффициентов перед многочленами Чебышева (см.выше)
x = np.array([3])
c = np.array([2])
POL.chebyshev.chebval(x,c)

NameError: name 'np' is not defined

In [ ]:
def integer_collinear_vector(numbers, max_denominator=1000000):
    t = np.array([])
    for i in range(len(numbers)):
        if numbers[i] != 0:
            a = np.array([numbers[i]])
            t = np.concatenate((t, a))
    norma = np.min(t)
    numbers = [num / norma for num in numbers]
    fracts = [fractions.Fraction(f).limit_denominator(max_denominator) for f in numbers]
    denoms = [f.denominator for f in fracts]
    denoms_gcd = functools.reduce(math.gcd, denoms)
    denoms_lcm = functools.reduce(lambda a, b: a*b, [d // denoms_gcd for d in denoms]) * denoms_gcd
    result_integers = [f.numerator * (denoms_lcm // f.denominator) for f in fracts]
    return result_integers

In [ ]:
A = np.array([[18, 6, 0], [6, 6, -7], [0, -7, 18]])
B = np.linalg.inv(A)
D = np.di
E = np.identity(3)
np.linalg.eig(B)

$\textbf{Интерполяция данных обобщёнными многочленами}$

In [1]:
#Не протестирована
#Здесь P - семейство функций, по первому индексу (целое число), выдающий функцию с данным номером, а по второму значение функции
def QPolyInterpolation (P, k, X, Y):
    print((i(P, k[0])(X[0]))
    A = np.array([[disc_scal(i(P, k[l]), i(P, k[j]), X) for j in range(len(k))] for l in range(len(k))])
    PS = np.array([[P[i][X[j]] for j in range(len(X))] for j in range(len(k))])
    F = PS@Y
    return LA.solve(A, F)

SyntaxError: invalid syntax (<ipython-input-1-d9e99b698964>, line 5)

In [ ]:
def f1(a, b):
    return a + b
def b(f, x, y):
    return f(x, y)

In [ ]:
b(f1, 1, 2)

In [ ]:
for i in range(1):
    print(i)

In [ ]:
def Newton_Form_Iteration(f, x, p):
    F = np.array([[(f(x[n:(n + p + 1)]) - f(x[(n - 1):(n + p)]))/(x[n + p - 1] - x[n])]

In [19]:
def ref(X, Y):
    D = [X[i+1] - X[i] for i in range(len(X) - 1)]
    F = [Y[i + 1] - Y[i] for i in range(len(Y) - 1)]
    return D, F
def iteration (D, F):
    D = [D[i+1] + D[i] for i in range(len(X) - 1)]
    F = [F[i+1] - F[i] for i in range(len(X) - 1)]
    return D, F
def answ (D, F):
    return np.array([F[i]/D[i] for i in range(len(D))], float)

X = np.array([0, 1, 2, 3, 4], float)
Y = np.array([1, 0.86603, 0.5, 0., -0.5])
ref(X, Y)
answ(ref(X, Y)[0], ref(X,Y)[1])

array([-0.13397, -0.36603, -0.5    , -0.5    ])