In [7]:
import itertools as it
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import functools
import math
import fractions
from scipy.interpolate import lagrange

from numpy import linalg as LA
#МПИ
def SimpleIteration(R, x, F):#R - матрица, x - столбец, F - правая часть (столбец)
    T = R@x + F
    return (T)
#МПИ k раз
def SimpleIterations(R,x,F,k):#R - матрица, x - столбец с которого итерируемся, F - правая часть(столбец), k- число итераций
    for i in range(k):
        x = SimpleIteration(R, x, F)
    return x
#k итераций методом Гаусса - Якоби 
def GaussJacobyIterations(A, x, F, k):#A - матрица, x - столбец с которого итерируемся, F - правая часть, k- число итераций
            D = np.diag(np.diag(A))
            Q = np.identity(len(A))
            G = np.identity(len(A))
            for i in range(len(A)):
                Q[i][i] = 1/D[i][i]
            R = -Q@(A - D)
            f = Q@F
            return SimpleIterations(R, x, f, k)
#Скалярное произведение
def scal(u, v):#u, v - сомножители (столбцы)
    return u@np.transpose(v)
#Итерационный метод вычисления максимального собственного вектора
def MaxEigenIterations(A, x, k):#A - матрица, x - вектор с которого итерируемся, k -число итераций
    u = SimpleIterations(A, x, 0, k-1)
    return scal(SimpleIteration(A,u,0), u)/scal(u, u)

In [2]:
A = np.array([[20, -1, 2, -3], [2, 20, -3, 4], [-3, 2, 20, -1],[-3,2,-1,20]], float)
D = np.diag(np.diag(A))
E = np.identity(4)
R = LA.inv(D)@A - E
print(R)
LA.norm(R, np.inf)
LA.norm(LA.inv((np.tril(A)@np.triu(A))))

[[ 0.   -0.05  0.1  -0.15]
 [ 0.1   0.   -0.15  0.2 ]
 [-0.15  0.1   0.   -0.05]
 [-0.15  0.1  -0.05  0.  ]]


0.0051242326227329835

In [3]:
def AbsMax(A):
    return np.max(np.array([np.max(A), -np.min(A)]))

In [4]:
A = np.array([[3, 1], [1, 2]])
x = np.array([0, 0])
F = np.array([1, -1])
np.linalg.solve(A, F)

array([ 0.6, -0.8])

In [5]:
r = np.array([[0.1, 0.20, 0.0], [0.20, -0.10, 0.10], [-0.30, 0.0, 0.20]])
f = np.array([-3.0, 2.0, -1.0])
R = np.array([[0,2/9,0], [2/11, 0, 1/11], [-3/8, 0, 0]])
F = np.array([-30/9, 20/11, -10/8])
x = np.array([0, 0, 0])
print(r)
for i in range(100):
    x = r@x + f
print("1:", x)
for i in range(100):
    x = R@x + F
print("2:",x)


[[ 0.1  0.2  0. ]
 [ 0.2 -0.1  0.1]
 [-0.3  0.   0.2]]
1: [-3.05483029  1.25326371 -0.10443864]
2: [-3.05483029  1.25326371 -0.10443864]


In [6]:
def IntVect(v, maxnum):
    answ = 0
    norm = np.linalg.norm(v)
    for k in range(1, maxnum):
        q = k*v
        approx = np.array([0 for i in range(len(v))])
        for i in range(len(v)):
            if (q[i] - int(q[i])) < (int(q[i]) + 1 - q[i]):
                approx[i] = int(q[i])
            else:
                approx[i] = int(q[i]) + 1
        if k == 1:
            norm = np.linalg.norm(q - approx, 2)
        else:
            if np.linalg.norm(q - approx) < norm:
                answ = approx
                norm = np.linalg.norm(q -approx)
    return (answ, q)


In [7]:
def SpecRad (A):
        return AbsMax(np.linalg.eig(A)[0])

In [8]:
A = np.array([[2, 1],[1, 2]])
OptRel(A)

NameError: name 'OptRel' is not defined

In [ ]:
def OptRel(A):
    D = np.diag(A)
    Q = np.identity(len(A))
    G = np.identity(len(A))
    for i in range(len(A)):
        Q[i][i] = 1/D[i]
        G[i][i] = D[i]
    R = -Q@(A - G)
    return (2/(1 + (1 - (SpecRad(R))**2)**0.5)
    


In [ ]:
A = np.array([[2, 1], [1, 2]], float)
f = np.array([1, 0], float)
x = np.array([0, 0], float)
GaussJacobyIterations(A, x, f, 100)

$u^{(s+1)} = u^{(s)} + \tau (f - Au^{(s)})$

Метод вращений.

$T^TAT = \Lambda$

$\tan (2\alpha) = \frac{2a_{ij}}{a_{ii} - a_{jj}}$

МНК:

$\Phi(\vec{u}) = \Sigma_i (\Sigma_j a_{ij}u_j - f_i)^2 \rightarrow min$

$A_{nxm}\vec{u}_n = \vec{f}_m$

$(A*A)_{nxn}\vec{u} = (A*f)_n$

Полиномы Чебышева $T_j(x)$
<br>
Их линейная комбинация:
<br>
$P_k(x) = \sum_{j = 0}^{k} c_jT_j(x)$

In [ ]:
import numpy as np
from numpy import polynomial as POL

In [ ]:
#x - вектор точек в которых необходимо узнать значения линейной комбинации многочленов Чебышева
#c - вектор коэффициентов перед многочленами Чебышева (см.выше)
x = np.array([3])
c = np.array([2])
POL.chebyshev.chebval(x,c)

$\textbf{Метод наискорейшего спуска}$

In [ ]:
#A - матрица, u - начальный ветор, f - правая часть, k - число итераций
def desc (A, u, f ,k):
    for i in range(k):
        r = A@u - f
        if(scal(r,r) == 0):
            return u
        t = scal(r, r)/scal(A@r, r)
        u = u - t*r
    return u


In [ ]:
#A - матрица, u - начальный ветор, f - правая часть, k - число итераций
def minnev (A, u, f ,k):
    for i in range(k):
        r = A@u - f
        if(scal(r,r) == 0):
            return u
        t = scal(A@r, r)/scal(A@r, A@r)
        u = u - t*r
    return u


In [ ]:
A = np.array([[10*j + i for i in range(10)] for j in range(10)])
print(A)

In [ ]:
#Интерполяция многочленом проходящим через заданную сетку
def SimplePolynomialInterpolation(x, y):
    A = np.array([[x[j]**i for i in range(len(y))] for j in range(len(x))])
    return np.linalg.solve(A, y)

In [ ]:
x = np.array([0, 1])
y = np.array([1, 0])
SimplePolynomialInterpolation(x, y)

In [ ]:
def integer_collinear_vector(numbers, max_denominator=1000000):
    t = np.array([])
    for i in range(len(numbers)):
        if numbers[i] != 0:
            a = np.array([numbers[i]])
            t = np.concatenate((t, a))
    norma = np.min(t)
    numbers = [num / norma for num in numbers]
    fracts = [fractions.Fraction(f).limit_denominator(max_denominator) for f in numbers]
    denoms = [f.denominator for f in fracts]
    denoms_gcd = functools.reduce(math.gcd, denoms)
    denoms_lcm = functools.reduce(lambda a, b: a*b, [d // denoms_gcd for d in denoms]) * denoms_gcd
    result_integers = [f.numerator * (denoms_lcm // f.denominator) for f in fracts]
    return result_integers

In [ ]:
A = np.array([[18, 6, 0], [6, 6, -7], [0, -7, 18]])
B = np.linalg.inv(A)
D = np.di
E = np.identity(3)
np.linalg.eig(B)

In [ ]:
33.7/3**0.5

In [ ]:
def f1(a, b):
    return a + b
def b(f, x, y):
    return f(x, y)

In [ ]:
b(f1, 1, 2)

In [ ]:
for i in range(1):
    print(i)

In [ ]:
def Newton_Form_Iteration(f, x, p):
    F = np.array([[(f(x[n:(n + p + 1)]) - f(x[(n - 1):(n + p)]))/(x[n + p - 1] - x[n])]

In [19]:
def ref(X, Y):
    D = [X[i+1] - X[i] for i in range(len(X) - 1)]
    F = [Y[i + 1] - Y[i] for i in range(len(Y) - 1)]
    return D, F
def iteration (D, F):
    D = [D[i+1] + D[i] for i in range(len(X) - 1)]
    F = [F[i+1] - F[i] for i in range(len(X) - 1)]
    return D, F
def answ (D, F):
    return np.array([F[i]/D[i] for i in range(len(D))], float)

X = np.array([0, 1, 2, 3, 4], float)
Y = np.array([1, 0.86603, 0.5, 0., -0.5])
ref(X, Y)
answ(ref(X, Y)[0], ref(X,Y)[1])

array([-0.13397, -0.36603, -0.5    , -0.5    ])

$\textbf{Формула Ньютона - Котеса}$

$\int_{a}^{b} f(x)dx= \sum_{i = 0}^{n - 1} f(\xi_i)(x_{i + 1} - x_{i})$

$\xi_i = \frac{x_{i+1} - x_{i}}{2}$



In [27]:
def SimInt (X, Y):
    S = 0.
    for i in range(len(X) - 1):
        S += (Y[i] + Y[i + 1])*(X[i + 1] - X[i])/2
#        print((Y[i] + Y[i+1])*(X[i + 1] - X[i])/2)
    return S


$\textbf{Формула трапеции}$

$\int_{a}^{b} f(x)dx= \sum_{i = 0}^{n - 1} \frac{(f(x_i) + f(x_{i + 1})}{2}(x_{i + 1} - x_{i})$

$\xi_i = \frac{x_{i+1} - x_{i}}{2}$

In [16]:
def TrapInt (X, Y):
    S = 0.
    for i in range(len(X) - 1):
        S += (Y[i] + Y[i + 1])*(X[i + 1] - X[i])/2
#        print((Y[i] + Y[i+1])*(X[i + 1] - X[i])/2)
    return S

$\textbf{Квадратуры Гаусса}$
$\int_{a}^{b} f(x)dx = \sum_{i = 1}^{n}c_i f(x_i)

$\{c_i\}$ - веса квадратур (n штук)

$\{x_i\}$ - узлы квадратур (n штук)

Требуем, чтобы формула была точна для многочленов как можно большей степени

$\frac{b^k - a^k}{k + 1} = \sum_{i = 1}^{n} c_i (x_i)^k$

In [29]:
X = np.array([0.000, 0.125, 0.25, 0.375, 0.5, 0.625, 0.750, 0.875, 1.000], float)
Y = np.array([1.0000, 0.984615, 0.941176, 0.876712, 0.8, 0.719101, 0.64, 0.566372, 0.5], float)
TrapInt(X,Y)

0.7847469999999999

$\textbf{Формула Эйлера-Маклорена}$
$\int_{a}^{b}f(x)dx = \sum_{i = 0}^{n}(\frac{(f(x_i) + f(x_{i + 1}))}{2}(x_{i + 1} - x_i) - \frac{(x_{i+1} - x_{i})^2}{2}(f'(x_{i+1}) - f'(x_{i}))$

In [23]:
def EuMac(X , Y, U):
    S = 0.
    for i in range(len(X) - 1):
        S += (Y[i] + Y[i + 1])*(X[i + 1] - X[i])/2 - ((X[i + 1] - X[i])**2)*(U[i + 1] - U[i])/2
        #print((Y[i] + Y[i+1])*(X[i + 1] - X[i])/2)
    return S


$\textbf{Вычисление интегралов от функций с особенностями.}$

1.Несобственные интегралы 1,2 рода.

2.Интегралы от быстроосциллирующих функций

Пример:

$$I = \int_0^1\frac{\cos(x)}{\sqrt(x)}dx$$

Для интегрирования неограниченных функций комбинируют аналитические и численные методы.\\
1)Замена переменной

$$I = | x = t^2 | = 2\int_0^1\cos(t^2)dt$$

2)Интегрирование по частям

$$I = 2\sqrt x \cos(x)|_0^1 + 2\int_0^1\sqrt x\sin(x)dx$$ (Особенность пропала)

3)Метод явного выделения особенности Канторовича

$$I = \int_0^1\frac{\cos(x)}{\sqrt(x)}dx = \int_0^1\frac{1}{\sqrt(x)}dx + \int_0^1\frac{\cos(x) - 1}{\sqrt(x)}dx = 2\sqrt(x)|_0^1 - 2\int_0^1\frac{\sin^2(\frac{x}{2})}{\sqrt x}dx$$

4) Разложение в ряд
$$I = \int\limits_0^{\delta} \frac{\cos x}{\sqrt{x}} \, dx + \int\limits_{\delta}^{1} \frac{\cos x}{\sqrt{x}} \, dx = \int\limits_0^{\delta} \frac{1 - x^2/2 + x^4/24 + ...}{\sqrt{x}} \, dx + \int\limits_{\delta}^{1} \frac{\cos x}{\sqrt{x}} \, dx$$




Задача:
Описать алгортм вычисления методом трапеций для заданной функции.

$\int_0^{\frac{\pi}{2}}\ln (\sin (x))dx$ - с точностью $\epsilon = 10^{-4}$

Решение:

$$\int_0^\frac{\pi}{2}\ln(\sin(x))dx = \int_0^{\frac{\pi}{2}}\ln(\frac{\sin(x)}{x})dx = (x\ln(x) - x)|_0^{\frac{\pi}{2}} + \int_0^{\frac{\pi}{2}}\ln(\frac{\sin(x)}{x})dx $$

 Задача:
 
 

$\textbf{Численное решение ОДУ}$

1)Коши

2)Краевые задачи

3)Спектральные задачи

$\textbf{Основные определения}$

Диф. задача:
$\mathcal{L}u = f,\ u(x_0)=u_0$

Сопоставляется:

Разностная схема:
$Ly = \varphi,\ y_0 = u_0 + ...$


$\textbf{Опр}$

Разностная задача сходится к решению дифференциальной задачи, если $||[u]_{h} - y||_{Y}\rightarrow 0$ при $h\rightarrow 0$

$[u]_h = \{u_m\}_{m=0}^N$

Примеры разностных схем:

1) Явная схема Эйлера:

$\frac{y_{m+1} - y_{m}}{h} = f(x_m, y_m)$

$y_0 = u_0$


2) Неявная схема Эйлера

$\frac{y_{m+1} - y_{m}}{h} = f(x_{m+1}, y_{m+1})$

$y_0 = u_0$

3) Схема с центральной разностью:

$\frac{y_{m+1} - y_{m-1}}{2h} = f(x_{m}, y_{m})$

$y_{0} = u_{0}$

Необх $y_{1} = ?$

4) Метод трапеций

$\frac{y_{m+1} - y_{m}}{h} = \frac{1}{2}(f_{m} + f_{m+1})$

5) Схема Эйлера с пересчётом

предиктор

$\frac{y_{m+\frac{1}{2}} - y_{m}}{\frac{h}{2}} = f_{m}$

корректор

$\frac{y_{m+1} - y_{m}}{h} = f(x_{m} + \frac{h}{2}, y_{m + \frac{1}{2}})$

$||[u]_{h} - y||_{Y} \leq c\cdot h^{p}$

Сходимость порядка p. c - сеточно независимая константа

\textbf{Задача} Доказать сходимость и определить порядок сходимости метода трапеций для решения задачи:

$u' = -8u$

$u(0) = 2$

Решение:

$u(x) = 2e^{-8x}$

$[u]^m_h = 2e^{-7x)m} = 2e^{-8mh}$

$\frac{y_{m+1} - y_{m}}{h} = -8\frac{1}{2}(y_{m} + y_{m+1})$

$y_{m+1} = y_{m}\frac{1-4h}{1+4h}$

$y_{m+1} = y_0(\frac{1 - 4h}{1 + 4h})^m$

$||[u]_h - y|| = max_{0\leq m\leq N}|2e^{-8mh} - 2(\frac{1 - 4h}{1 + 4h})^m| = 2max_{0\leq m\leq N}|e^{-8mh} - e^{m(ln(1 - 4h)- ln(1 + 4h))}|\leq 2\cdot \frac{128}{3}mh^3 = 2 \frac{128}{3} X h^2$

$\textbf{Определение}$
Невязкой разностной схемы называется результат подстановки в разностную схему сеточной проекции точного решения диф. задачи.
$r_h = L[u]_h - \varphi$

$\textbf{Определение:}Разностная схема называется аппроксимирующей данную дифференциальную систему, если $r_h \rightarrow 0 при h\rightarrow 0$

$\textbf{Определение} Разн. задача устойчива, если \exists h_0\exists \epsilon : \forall h\leq h_0, \forall \epsilon^{(1)}, \epsilon^{(2)}: ||\epsilon^{(1)}||\leq \epsilon, ||\epsilon^{(2)}||\leq \epsilon$

Для решения возмущённых задач:

$Ly^{(2)} = \varphi + \epsilon^{(1)}$
    
$Ly^{(1)} = \varphi + \epsilon^{(2)}$

Выполнено:

$||y^{(1)} - y^{(2)}||\leq c_2(||\epsilon^{(1)} + \epsilon^{(2)}||)$

Теорема:(Лакса-Рябенького-Филиппова)
Если разностная задача аппроксимирует дифференциальную и устойчива, то решение разностной задачи сходится к решению дифференциальной (по норме), причём порядок сходимости равен порядку аппроксимации.

$Ly = \varphi$

$L[u]_h = \varphi + r_h$

И задача устойчиваа, то $||y - u_h||\leq c||r_h||$