In [134]:
import numpy as np
#МПИ
def SimpleIteration(R, x, F):#R - матрица, x - столбец, F - правая часть (столбец)
    return (R@x + F)
#МПИ k раз
def SimpleIterations(R,x,F,k):#R - матрица, x - столбец с которого итерируемся, F - правая часть(столбец), k- число итераций
    for i in range(k):
        x = SimpleIteration(R, x, F)
    return x
#k итераций методом Гаусса
def GaussIterations(A, x, F, k):#A - матрица, x - столбец с которого итерируемся, F - правая часть, k- число итераций
            D = np.diag(A)
            U = np.triu(A)
            L = np.tril(A)
            Q = np.identitynty(len(A))
            for i in range(len(A)):
                Q[i,i] = 1/D[i,i]
            R = -Q@(L + U)
            f = Q@F
            return SimpleIterations()
def scal(u, v):#u, v - сомножители (столбцы)
    return u@np.transpose(v)
def MaxEigenIterations(A, x, k):#A - матрица, x - вектор с которого итерируемся, k -число итераций
    u = SimpleIterations(A, x, 0, k-1)
    return scal(SimpleIteration(A,u,0), u)/scal(u, u)

    

Памятка:

Вычисление норм:

numpy.linalg.

In [136]:
A = np.array([[5, -2],[-2, 2]], float)
MaxEigenIterations(A, np.array([1, 0], float), 2)

5.9655172413793105

In [44]:
r = np.array([[0, 1], [1, 0]], float)
x = np.array([0, 1], float)
f = np.array([1, 2], float)
SimpleIteration(r, x, f)


/home/andrey/home/andrey/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


array([[1. , inf, inf],
       [inf, 1. , inf],
       [inf, inf, 0.5]])

In [121]:
r = np.array([[5,2,-3],[4,5,-4],[6,4,-4]])
E = np.identity(3)
f = np.array([4,5,6])
x = np.array([1,0,0])
SimpleIterations(E - 0.5*r, x, 0.5*f, 0)


array([1, 0, 0])

$u^{(s+1)} = u^{(s)} + \tau (f - Au^{(s)})$

Метод вращений.

$T^TAT = \Lambda$

$\tan (2\alpha) = \frac{2a_{ij}}{a_{ii} - a_{jj}}$

МНК

$\Phi(\vec{u}) = \Sigma_i (\Sigma_j a_{ij}u_j - f_i)^2 \rightarrow min$

$A_{nxm}\vec{u}_n = \vec{f}_m$

$(A*A)_{nxn}\vec{u} = (A*f)_n$

In [142]:
A = np.array([[1,1], [2,-1], [1,3],[3, 1]])
f = np.array([3, 0.2, 7.0, 5.0])
np.linalg.inv(np.transpose(A)@A)@(np.transpose(A)@f)
scal(())

array([1.03741935, 1.96774194])